# Generated by Django 4.1.2 on 2022-11-10 08:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tomato_url', models.TextField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('imdb_id', models.CharField(max_length=10, unique=True)),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('priority', models.FloatField()),
                ('plot', models.TextField()),
                ('runtime', models.IntegerField()),
                ('poster_url', models.TextField()),
                ('mpa_rating', models.CharField(max_length=10)),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('tomato_rating', models.IntegerField()),
                ('awards', models.CharField(max_length=256)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('writers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uurl', models.TextField(db_index=True)),
                ('rating', models.IntegerField()),
                ('tomato_url', models.TextField()),
            ],
        ),
    ]
