-- SELECT * from get_recs('[{"tomato_url":"robot-jox","rating":9},{"tomato_url":"fight_club","rating":10},{"tomato_url":"the_red_violin","rating":10},{"tomato_url":"meet_the_parents_1992","rating":2},{"tomato_url":"return_of_the_living_dead_3","rating":6},{"tomato_url":"hellraiser","rating":10},{"tomato_url":"ernest-scared-stupid","rating":8},{"tomato_url":"great_outdoors","rating":10},{"tomato_url":"american_beauty","rating":10},{"tomato_url":"the_addams_family","rating":10},{"tomato_url":"addams_family_values","rating":10},{"tomato_url":"stairway_to_heaven_1946","rating":8},{"tomato_url":"the_dark_knight","rating":10},{"tomato_url":"october_sky","rating":6},{"tomato_url":"meet_joe_black","rating":10},{"tomato_url":"star_trek_first_contact","rating":10},{"tomato_url":"1084146-thin_red_line","rating":6},{"tomato_url":"sister_act","rating":6},{"tomato_url":"40_year_old_virgin","rating":8}]'::json);
-- SELECT * from give_vector('[{"tomato_url":"robot-jox","rating":9}]'::json);
-- SELECT * FROM give_vector('[{"tomato_url":"fight_club","rating":10},{"tomato_url":"pulp_fiction","rating":9},{"tomato_url":"shawshank_redemption","rating":10},{"tomato_url":"the_dark_knight","rating":5},{"tomato_url":"inception","rating":9},{"tomato_url":"matrix","rating":8},{"tomato_url":"interstellar_2014","rating":4},{"tomato_url":"saving_private_ryan","rating":7},{"tomato_url":"the_lion_king","rating":10},{"tomato_url":"star_wars","rating":9}]'::json);
-- SELECT * from r_version();
-- SELECT * FROM get_recs('[{"tomato_url":"fight_club","rating":10},{"tomato_url":"pulp_fiction","rating":9},{"tomato_url":"shawshank_redemption","rating":10},{"tomato_url":"the_dark_knight","rating":5},{"tomato_url":"inception","rating":9},{"tomato_url":"matrix","rating":8},{"tomato_url":"interstellar_2014","rating":4},{"tomato_url":"saving_private_ryan","rating":7},{"tomato_url":"the_lion_king","rating":10},{"tomato_url":"star_wars","rating":9}]'::json);
SELECT * FROM get_recs('[{"tomato_url":"robot-jox","rating":9},{"tomato_url":"fight_club","rating":10},{"tomato_url":"the_red_violin","rating":10},{"tomato_url":"meet_the_parents_1992","rating":2},{"tomato_url":"return_of_the_living_dead_3","rating":6},{"tomato_url":"hellraiser","rating":10},{"tomato_url":"ernest-scared-stupid","rating":8},{"tomato_url":"great_outdoors","rating":10},{"tomato_url":"american_beauty","rating":10},{"tomato_url":"the_addams_family","rating":10},{"tomato_url":"addams_family_values","rating":10},{"tomato_url":"stairway_to_heaven_1946","rating":8},{"tomato_url":"the_dark_knight","rating":10},{"tomato_url":"october_sky","rating":6},{"tomato_url":"meet_joe_black","rating":10},{"tomato_url":"star_trek_first_contact","rating":10},{"tomato_url":"1084146-thin_red_line","rating":6},{"tomato_url":"sister_act","rating":6},{"tomato_url":"40_year_old_virgin","rating":8},{"tomato_url":"slc_punk","rating":10},{"tomato_url":"starship_troopers","rating":9},{"tomato_url":"crow","rating":9},{"tomato_url":"fiddler_on_the_roof","rating":10},{"tomato_url":"event_horizon","rating":10},{"tomato_url":"no_country_for_old_men","rating":10},{"tomato_url":"there_will_be_blood","rating":10},{"tomato_url":"citizen_kane","rating":5},{"tomato_url":"dr_strangelove","rating":7},{"tomato_url":"iron_man_3","rating":6},{"tomato_url":"schindlers_list","rating":10},{"tomato_url":"matrix","rating":10},{"tomato_url":"memento","rating":5},{"tomato_url":"1003707-casablanca","rating":5},{"tomato_url":"1074316-scream","rating":6}]'::json);
-- SELECT * FROM get_recs('[{"tomato_url":"the-last-dragon","rating":9},{"tomato_url":"iron_giant","rating":10},{"tomato_url":"summer-wars","rating":8},{"tomato_url":"nausicaa_of_the_valley_of_the_wind","rating":9},{"tomato_url":"dragon_ball_z_resurrection_f","rating":8},{"tomato_url":"ready_player_one","rating":3}]'::json);
-- SELECT * FROM get_recs('[{"tomato_url":"slc_punk","rating":10},{"tomato_url":"starship_troopers","rating":9},{"tomato_url":"crow","rating":9},{"tomato_url":"fiddler_on_the_roof","rating":10},{"tomato_url":"event_horizon","rating":10},{"tomato_url":"no_country_for_old_men","rating":10},{"tomato_url":"robot-jox","rating":8},{"tomato_url":"meet_the_parents_1992","rating":2}]'::json);
-- SELECT * FROM get_recs('[{"tomato_url":"slc_punk","rating":10},{"tomato_url":"starship_troopers","rating":9},{"tomato_url":"crow","rating":9},{"tomato_url":"fiddler_on_the_roof","rating":10},{"tomato_url":"event_horizon","rating":10},{"tomato_url":"no_country_for_old_men","rating":10},{"tomato_url":"robot-jox","rating":8},{"tomato_url":"meet_the_parents_1992","rating":2},{"tomato_url":"dr_strangelove","rating":0}]'::json);
-- SELECT * from get_recs('[{"tomato_url":"robot-jox","rating":10}]'::json);

